#!/bin/bash

count_state() {
  awk '!/STAT/ { stat[$0] += 1 } END { for (i in stat) print "opennebula_'"$1"'_count{state=\""i"\"}", stat[i] }'
}

onehost_count() {
  onehost list --csv --list STAT | count_state host
}

onevm_count() {
  onevm list --csv --list STAT | count_state vm
}

onedatastore_count() {
  onedatastore list --csv --list STAT | count_state datastore
}

oneimage_count() {
  oneimage list --csv --list STAT | count_state image
}

gen_tags() {
  local TAG_PATH="$1"
  shift
  echo -n '-o "{"'
  NUM=0
  while (( "$#" )); do
    if [ $NUM -gt 0 ]; then
      echo -n ","
    fi
    echo -n " -o \"${1,,}=\\\"\" -v \"${TAG_PATH}/${1^^}\" -o \\\""
    shift
    local NUM=$(($NUM+1))
  done
  echo -n ' -o "} "'
}

onehost_metrics_keys() {
  local NAME="$1"
  local TAGS_L0="$(gen_tags .. ID NAME CLUSTER)"
  local TAGS_L1="$(gen_tags ../.. ID NAME CLUSTER)"
  shift
  while (( "$#" )); do
    case ${1^^} in
      STATE|LAST_MON_TIME)
        echo -n " -t -m 'HOST_POOL/HOST/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L0 -v . -n"
      ;;
      DISK_USAGE|MEM_USAGE|CPU_USAGE|TOTAL_MEM|TOTAL_CPU|MAX_DISK|MAX_MEM|MAX_CPU|FREE_DISK|FREE_MEM|FREE_CPU|USED_DISK|USED_MEM|USED_CPU|RUNNING_VMS)
        echo -n " -t -m 'HOST_POOL/HOST/HOST_SHARE/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L1 -v . -n"
      ;;
      CPUSPEED|NETRX|NETTX|RESERVED_CPU|RESERVED_MEM)
        echo -n " -t -m 'HOST_POOL/HOST/TEMPLATE/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L1 -v . -n"
      ;;
    esac
    shift
  done
  echo
}

onevm_metrics_keys() {
  local NAME="$1"
  local TAGS_L0="$(gen_tags .. ID UID GID NAME UNAME GNAME)"
  local TAGS_L1="$(gen_tags ../.. ID UID GID NAME UNAME GNAME)"
  shift
  while (( "$#" )); do
    local PARAM=${1^^}
    case $PARAM in
      STATE|LCM_STATE|LAST_MON_TIME|STIME|ETIME|LAST_POLL)
        echo -n " -t -m 'VM_POOL/VM/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L0 -v . -n"
      ;;
      TOTAL_CPU|TOTAL_MEM|USED_CPU|USED_MEM)
        if [ "${PARAM%%_*}" = "TOTAL" ]; then
          local FROM=TEMPLATE
        else
          local FROM=MONITORING
        fi
        if [ "${PARAM##*_}" = "MEM" ]; then
          local PARAM=MEMORY
        else
          local PARAM="${PARAM##*_}"
        fi
        echo -n " -t -m 'VM_POOL/VM/$FROM/$PARAM[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L1 -v . -n"
      ;;
    esac
    shift
  done
  echo
}

onedatastore_metrics_keys() {
  local NAME="$1"
  local TAGS_L0="$(gen_tags .. ID UID GID NAME UNAME GNAME)"
  shift
  while (( "$#" )); do
    case ${1^^} in
      STATE|TOTAL_MB|FREE_MB|USED_MB)
        echo -n " -t -m 'DATASTORE_POOL/DATASTORE/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L0 -v . -n"
      ;;
      IMAGES|CLUSTERS)
        echo -n " -t -m 'DATASTORE_POOL/DATASTORE/${1^^}' -o '${NAME,,}_${1,,}' $TAGS_L0 -v 'count(ID)' -n"
      ;;
    esac
    shift
  done
  echo
}

onevnet_metrics_keys() {
  local NAME="$1"
  local TAGS_L0="$(gen_tags .. ID UID GID NAME UNAME GNAME)"
  shift
  while (( "$#" )); do
    case ${1^^} in
      SIZE)
        echo -n " -t -m 'VNET_POOL/VNET/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L0 -v 'sum(AR/${1^^})' -n"
      ;;
      USED_LEASES)
        echo -n " -t -m 'VNET_POOL/VNET/${1^^}[string-length(text()) > 0]' -o '${NAME,,}_${1,,}' $TAGS_L0 -v . -n"
      ;;
      CLUSTERS|VROUTERS)
        echo -n " -t -m 'VNET_POOL/VNET/${1^^}' -o '${NAME,,}_${1,,}' $TAGS_L0 -v 'count(ID)' -n"
      ;;
    esac
    shift
  done
  echo
}

onehost_metrics() {
  local METRICS=${@:-STATE DISK_USAGE MEM_USAGE CPU_USAGE TOTAL_MEM TOTAL_CPU MAX_DISK MAX_MEM MAX_CPU FREE_DISK FREE_MEM FREE_CPU USED_DISK USED_MEM USED_CPU CPUSPEED NETRX NETTX RESERVED_CPU RESERVED_MEM}
  eval "onehost list -x | xmlstarlet sel $(onehost_metrics_keys opennebula_host $METRICS)"
}

onevm_metrics() {
  local METRICS=${@:-STATE LCM_STATE TOTAL_CPU USED_CPU TOTAL_MEM USED_MEM}
  eval "onevm list -x | xmlstarlet sel $(onevm_metrics_keys opennebula_vm $METRICS)"
}

onedatastore_metrics() {
  local METRICS=${@:-STATE TOTAL_MB FREE_MB USED_MB}
  eval "onedatastore list -x | xmlstarlet sel $(onedatastore_metrics_keys opennebula_datastore $METRICS)"
}

onevnet_metrics() {
  local METRICS=${@:-SIZE USED_LEASES}
  eval "onevnet list -x | xmlstarlet sel $(onevnet_metrics_keys opennebula_vnets $METRICS)"
}

## Common statistic
#onehost_count
#onevm_count
#onedatastore_count
#oneimage_count

# Detailed metrics
onehost_metrics
onevm_metrics
onedatastore_metrics
onevnet_metrics
